#!/usr/bin/env bash
# Initialize a _projects/ folder in the current repo (or a given base directory).
# Creates:
#   _projects/README.md   — the structure guide for the folder
#   _projects/CLAUDE.md   — symlink -> README.md, so Claude sessions pick up the conventions
#
# Usage: init-projects.sh [base-dir]   (default: current directory)
set -euo pipefail

BASE_DIR="${1:-.}"
PROJECTS_DIR="$BASE_DIR/_projects"

mkdir -p "$PROJECTS_DIR"

README="$PROJECTS_DIR/README.md"
if [[ -e "$README" ]]; then
  echo "already exists, leaving untouched: $README"
else
  cat > "$README" <<'EOF'
# _projects/

This folder holds one directory per project. It is the working area for
ad-hoc project files, notes, and todo lists.

## Structure

```
_projects/
  README.md                          # this file — the conventions for the folder
  CLAUDE.md                          # symlink -> README.md (so Claude sessions load these rules)
  YYYY-MM-DD--<project-name>/        # one folder per project, date-prefixed, kebab-case name
    todo.md                          # the project's todo list (format below)
    README.md                        # small random notes — MUST stay under 256 lines
    ...                              # any other ad-hoc files the project needs
```

## Project folders

- Every project lives in its own directory named `YYYY-MM-DD--<project-name>`,
  where the date is the day the project was started and the name is short and
  kebab-case (e.g. `2026-07-17--marketplace-redesign`).
- Store any ad-hoc files for the project inside its folder — scratch scripts,
  exports, drafts, whatever the project needs.

## todo.md format

Each project folder has a `todo.md` containing the project's todo list:

```markdown
# TODO — <project name>

- [ ] Write the launch announcement @high [assignee:brave-otter]
- [ ] Collect beta feedback @medium
- [x] Set up the repo @low [assignee:quiet-harbor]
```

- One task per line as a Markdown checkbox (`- [ ]` open, `- [x]` done).
- **Priorities** are @-mentions on the task line: `@high`, `@medium`, or `@low`.
- **Assignees** are linked by id with `[assignee:<id>]`. The id is a readable
  two-word session id (adjective-noun, e.g. `brave-otter`) generated by the
  `session-ids` plugin. A task may have zero or more assignees.

## Project README.md

Each project folder also has its own `README.md` for random small notes —
context, links, decisions, reminders.

- **Hard limit: keep every project README.md under 256 lines.** When a README
  approaches the limit, prune stale notes or move long-form content into a
  separate ad-hoc file in the project folder and link to it.

## CLAUDE.md symlink

`_projects/CLAUDE.md` is a symlink to this README so that any Claude session
reading or editing a project file understands how these files and folders are
organized. Do not replace the symlink with a regular file; edit this README
instead.
EOF
  echo "created: $README"
fi

# CLAUDE.md -> README.md symlink so Claude sessions load the conventions.
CLAUDE_LINK="$PROJECTS_DIR/CLAUDE.md"
if [[ -L "$CLAUDE_LINK" ]]; then
  echo "symlink already in place: $CLAUDE_LINK -> $(readlink "$CLAUDE_LINK")"
elif [[ -e "$CLAUDE_LINK" ]]; then
  echo "warning: $CLAUDE_LINK exists and is not a symlink; leaving it untouched" >&2
else
  ln -s README.md "$CLAUDE_LINK"
  echo "created symlink: $CLAUDE_LINK -> README.md"
fi

echo "done: $PROJECTS_DIR is ready"
