#!/usr/bin/env bash
# Scaffold a new project folder inside _projects/.
# Creates _projects/YYYY-MM-DD--<project-name>/ with todo.md and README.md.
#
# Usage: new-project.sh <project-name> [base-dir]
#   project-name  — free text; slugified to kebab-case
#   base-dir      — directory containing _projects/ (default: current directory)
set -euo pipefail

if [[ $# -lt 1 ]]; then
  echo "usage: new-project.sh <project-name> [base-dir]" >&2
  exit 1
fi

RAW_NAME="$1"
BASE_DIR="${2:-.}"
PROJECTS_DIR="$BASE_DIR/_projects"

# Slugify: lowercase, non-alphanumerics -> dashes, trim leading/trailing dashes.
SLUG="$(printf '%s' "$RAW_NAME" \
  | tr '[:upper:]' '[:lower:]' \
  | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//')"
if [[ -z "$SLUG" ]]; then
  echo "error: project name '$RAW_NAME' produced an empty slug" >&2
  exit 1
fi

if [[ ! -d "$PROJECTS_DIR" ]]; then
  echo "note: $PROJECTS_DIR does not exist yet — run init-projects.sh first (creating it bare for now)" >&2
  mkdir -p "$PROJECTS_DIR"
fi

DATE="$(date +%Y-%m-%d)"
PROJECT_DIR="$PROJECTS_DIR/$DATE--$SLUG"

if [[ -e "$PROJECT_DIR" ]]; then
  echo "error: $PROJECT_DIR already exists" >&2
  exit 1
fi
mkdir -p "$PROJECT_DIR"

cat > "$PROJECT_DIR/todo.md" <<EOF
# TODO — $SLUG

<!--
  Format (see ../README.md):
  - [ ] Task description @high|@medium|@low [assignee:<id>]
  Priorities are @-mentions; assignees are linked by readable session id
  (adjective-noun, generated by the session-ids plugin).
-->

- [ ] Define the goal of this project @high
EOF

cat > "$PROJECT_DIR/README.md" <<EOF
# $SLUG

Started $DATE. Random small notes for this project live here.

> Keep this file under 256 lines (see ../README.md). Move anything longer
> into its own file in this folder and link it.
EOF

echo "created: $PROJECT_DIR"
echo "  - todo.md"
echo "  - README.md"
