#!/usr/bin/env bash
# SessionStart hook: give this session a readable id (adjective-noun, e.g.
# "brave-otter"), persist it, and inject it as session context.
#
# Reads the SessionStart hook JSON on stdin (session_id, cwd, source, ...).
# State lives in ${CLAUDE_SESSION_IDS_DIR:-$HOME/.claude/session-ids}:
#   <session_id>.json  — one record per session
#   latest             — symlink to the most recently started/resumed record
#
# Resuming a session (source: resume/compact/clear) keeps its existing id.
set -euo pipefail

STATE_DIR="${CLAUDE_SESSION_IDS_DIR:-$HOME/.claude/session-ids}"
mkdir -p "$STATE_DIR"

INPUT="$(cat || true)"

# Minimal JSON string escaping for values interpolated into JSON below.
json_escape() {
  local s="$1"
  s="${s//\\/\\\\}"
  s="${s//\"/\\\"}"
  s="${s//$'\n'/\\n}"
  s="${s//$'\r'/\\r}"
  s="${s//$'\t'/\\t}"
  printf '%s' "$s"
}

# Pull a string field out of the hook JSON. Prefer python3, fall back to sed.
json_field() {
  local field="$1"
  if command -v python3 >/dev/null 2>&1; then
    printf '%s' "$INPUT" | python3 -c "
import json, sys
try:
    print(json.load(sys.stdin).get('$field') or '')
except Exception:
    pass
"
  else
    printf '%s' "$INPUT" | sed -n "s/.*\"$field\"[[:space:]]*:[[:space:]]*\"\([^\"]*\)\".*/\1/p" | head -1
  fi
}

SESSION_ID="$(json_field session_id)"
SOURCE="$(json_field source)"
CWD="$(json_field cwd)"
[[ -n "$SESSION_ID" ]] || SESSION_ID="unknown-$$"
# Filename-safe: the session id names the record file below.
SESSION_ID="$(printf '%s' "$SESSION_ID" | tr -c 'a-zA-Z0-9._-' '_')"

RECORD="$STATE_DIR/$SESSION_ID.json"

ADJECTIVES=(amber bold brave breezy bright calm clever cosmic crimson curious
  daring dapper eager fearless fluffy gentle gilded glad golden happy hardy
  humble jolly keen kind lively lucky mellow merry mighty nimble noble plucky
  proud quiet rustic silent silver snappy spry stellar sturdy sunny swift
  tidy velvet vivid wandering warm wise zesty)

NOUNS=(acorn badger beacon birch bison breeze brook canyon cedar comet coral
  crane dune ember falcon fern fjord fox gecko glacier harbor heron lagoon
  lantern lemur linden lynx maple meadow moose nebula orchard osprey otter
  pebble pine prairie quartz raven reef river sparrow summit thicket tundra
  walnut willow wren zephyr)

# Keep the existing id when this session already has one (resume/compact/clear).
if [[ -f "$RECORD" ]]; then
  READABLE_ID="$(sed -n 's/.*"readable_id"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$RECORD" | head -1)"
fi

if [[ -z "${READABLE_ID:-}" ]]; then
  READABLE_ID="${ADJECTIVES[RANDOM % ${#ADJECTIVES[@]}]}-${NOUNS[RANDOM % ${#NOUNS[@]}]}"
  STARTED_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
else
  STARTED_AT="$(sed -n 's/.*"started_at"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$RECORD" | head -1)"
  [[ -n "$STARTED_AT" ]] || STARTED_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
fi

cat > "$RECORD" <<EOF
{
  "readable_id": "$(json_escape "$READABLE_ID")",
  "session_id": "$(json_escape "$SESSION_ID")",
  "started_at": "$(json_escape "$STARTED_AT")",
  "last_seen_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "source": "$(json_escape "${SOURCE:-startup}")",
  "cwd": "$(json_escape "${CWD:-$PWD}")"
}
EOF

ln -sfn "$SESSION_ID.json" "$STATE_DIR/latest"

# Inject the id into the session's context.
CONTEXT="This session's readable id is \"$READABLE_ID\" (session_id: $SESSION_ID). Generated by the session-ids plugin; the session record is stored at $RECORD. Use this id when a task or todo needs an assignee id."

if command -v python3 >/dev/null 2>&1; then
  CONTEXT="$CONTEXT" python3 -c "
import json, os
print(json.dumps({'hookSpecificOutput': {'hookEventName': 'SessionStart', 'additionalContext': os.environ['CONTEXT']}}))
"
else
  printf '{"hookSpecificOutput":{"hookEventName":"SessionStart","additionalContext":"%s"}}\n' "$(json_escape "$CONTEXT")"
fi
